### PR TITLE
Attempt to solve issue #1

### PR DESCRIPTION
**Pull request by Vekat**
Trying to solve issue #1 by detecting a chat group and ignoring it with a message.

### CODE REVIEW

**Comment by vrcca** [comment]
Although I appreciate your contribution, this PR completely blocks any group messages. What we are trying to fix are mentions only.  So /commands should continue to work.

Examples:
/remember@advanced_alarm_bot <time> <text>  = OK
/remember <time> <text>  = OK

Hey, @advanced_alarm_bot! <time> <text>  = Not OK
Sup, @advanced_alarm_bot  = Not OK

I'll try to add some testing libraries.

**Comment by Vekat** [comment]
Hi @vrcca, I guess I should have asked before misinterpreting the problem.

These are the expected formats then?
* `/remember {input}`
* `/remember @advanced_alarm_bot {input}`

**Comment by vrcca** [comment]
According to [Telegram Bots FAQ](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get), yes. 

The second case should be "/remember@advanced_alarm_bot {input}", no spaces:
  + /remember {input}
  + /remember@advanced_alarm_bot {input}

**Comment by Vekat** [comment]
I see. In that case, I think the method `handleRemember` would need to be rewritten to parse the input even if the length of the command is different than 9 characters.

A quick and dirty solution would be to pass the command length as a parameter so you wouldn't need to rewrite your parsing function.

**Comment by vrcca** [comment]
Yes. Actually I'm refactoring the handleMessage method to a separe file. Handling messages has nothing to do with Telegram's API. 
In the actual state it's difficult to evolve the code, so I plan to rewrite it using TDD.

**Comment by Vekat** [comment]
That's a great idea.

**Pull request closed without merging**
